### PR TITLE
Update sonarr_discord.py

### PR DESCRIPTION
**Pull request by TRaSH-**
fixed typo for python3

### CODE REVIEW

**Comment by samwiseg0** [comment]
This is not an error. The container does not have python3. That is why there are 2 versions

```
# python
Python 2.7.17 (default, Nov  7 2019, 10:07:09)
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
root@45498dde6a4a:/# python3
bash: python3: command not found
```

**Comment by TRaSH-** [comment]
I think it depends on which image you're using.
The image I'm using updated a few months while ago to python 3.
hotio/sonarr
Didn't know the other images are still using a EOL version of python

**Comment by samwiseg0** [comment]
I was going based off the image the repo directly links to with is `linuxserver`.

**Comment by TRaSH-** [comment]
I just checked
https://github.com/Radarr/Radarr/wiki/Docker
They mention in the wiki both,
I chose the hotio one because the developer is in direct contact with the guys working on v3 and he also makes special images for just testing

**Pull request closed without merging**
